"""Project-wide constants for the safety-first foundation."""

PAPER_TRADING_ONLY = True
DISCLAIMER = "SIMULATED PAPER TRADING ONLY - NOT FINANCIAL ADVICE"

SUPPORTED_TRADING_CURRENCY = "USD"
SUPPORTED_DISPLAY_CURRENCY = "NIS"
